config/routes.rb
RottenMangoes::Application.routes.draw do
  
  root 'movies#index'
  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  namespace "admin" do
    resources :users, only: [:edit, :new, :create, :show, :update, :index, :destroy]
  end

  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews

  mount_uploader :image, ImageUploader

  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :release_date,
    presence: true

  #can not have reviews of a movie not yet released
  validate :release_date_is_in_the_past

  #could move all code from index here and filter in model instead
  def self.search(search)
    where("title LIKE ?", "%#{search}%")
  end

  #def review_average
    #reviews.sum(:rating_out_of_ten)/reviews.size
  #end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should probably be in the past") if release_date > Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }
    
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews

  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "#{@user.full_name} was created successfully!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user), notice: "#{@user.full_name} was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, notice: "User was deleted successfully"
    else
      render :edit
    end
  end

  protected

  def user_params
    params.require(:user).permit(
      :email, :firstname, :lastname, :password, :password_confirmation,
      :admin
    )
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin
  def require_admin
    unless current_user.admin
      redirect_to movies_path, notice: "#{current_user.full_name} is not an admin!"
    end
  end
  
end

app/controllers/application_controller.rb
require 'pry'
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @movies = @movies.where("title LIKE ?", "%#{params[:search_title]}%") if params[:search_title]
    @movies = @movies.where("director LIKE ?", "%#{params[:search_director]}%") if params[:search_director]
    @movies = @movies.where(runtime_in_minutes: 0..90) if (params[:search_runtime] && params[:search_runtime] == 'short')
    @movies = @movies.where(runtime_in_minutes: 90..120) if (params[:search_runtime] && params[:search_runtime] == 'medium')
    @movies = @movies.where("runtime_in_minutes > 120") if (params[:search_runtime] && params[:search_runtime] == 'long')
    @movies = @movies.order('title ASC')
  end

  #i want to DRY this up
  def show
    @movies = Movie.where(id: params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie), notice: "#{@movie.title} was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :image
    )
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log has failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "See you next time!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    binding.pry
    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user, url: admin_user_path) do |f| %>
    <% if @user.errors.any? %>
        <div>
            <%= pluralize(@user.errors.count, "error") %>
            <ul>
                <% @user.errors.full_messages.each do |msg| %> prevented this user from being signed up:
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
    </div>
    <div>
        <%= f.label :firstname, "First Name" %><br>
        <%= f.text_field :firstname %>
    </div>
    <div>
        <%= f.label :lastname, "Last Name" %><br>
        <%= f.text_field :lastname %>
    </div>
    <div>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
    </div>
    <div>
        <%= f.label :admin, "Admin Rights" %><br>
        <%= f.check_box :admin %>
    </div>
    <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<%= link_to "View all users", admin_users_path %>
<h1>Sign up: Admin edition</h1>
<%= render 'form' %>
<hr>
<%= link_to "Delete user", admin_user_path(@user), method: :delete %>
<hr>

app/views/admin/users/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Back to all movies", movies_path %></hr>
<!-- This path sounds weird. You can create a new user, doesnt
have to be an admin though. Can be a normal user -->
<%= link_to "Create new user", new_admin_user_path %></hr>
<hr>
<% @users.each do |user| %>
    <h2><%= link_to user.email, admin_user_path(user) %></h2>
    <h3><%= user.full_name %></h3>
    <hr>
<% end %></hr>
<%= paginate @users %>
<%= page_entries_info @users %>

app/views/admin/users/new.html.erb
<%= link_to "View all movies", movies_path %>
<h1>Sign up: Admin edition</h1>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Back to all users", admin_users_path %>
<hr>
<h2><%= @user.email %></h2>
<h3><%= @user.full_name %></h3>
<hr>
<%= link_to "Edit user", edit_admin_user_path %>
<hr>

app/views/layouts/_footer.html.erb
<footer>
<small>
    <% if current_user %>
        Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
        <% if current_user.admin %>
            You have administrative rights. Access <%= link_to "Users Index", admin_users_path %>
        <% end %>
    <% else %>
        <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
</small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: {multipart: true} do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
    <%= f.label "director" %><br>
    <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.text_field "runtime_in_minutes" %>
</div>
<p>
<%= f.file_field :image %>
</p>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_search.html.erb
<!-- strech goals full-text search... rubygem, and elastic search.
    weight results per density ala google -->
<%= form_tag(movies_path, method: 'get', id: 'search-form') do %>
    <p>Title: <%= text_field_tag :search_title, params[:search_title], placeholder: "Filter by title..." %></p>
    <p>Director: <%= text_field_tag :search_director, params[:search_director], placeholder: "Filter by director..." %></p>
    <p>Runtime: <%= select_tag(:search_runtime, options_for_select([['Any runtime', nil], ['Under 90 minutes', 'short'], ['Between 90 and 120 minutes', 'medium'], ['Over 120 minutes', 'long']])) %></p>
    <p><%= submit_tag "Search" %></p>
<% end %>
</br>
<% if @movies.present? %>
    <%= render 'show' %>
<% end %>

app/views/movies/_show.html.erb
<% @movies.each do |movie| %>
    <%= link_to image_tag(movie.image_url(:thumb).to_s), movie_path(movie) %>
    <h2><%= link_to movie.title, movie_path(movie) %></h2>
    <h3><%= movie.release_date %></h3>
    <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
    <p><%= movie.description %></p>
    <hr>
<% end %></hr>

app/views/movies/edit.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Edit a movie!</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Submit a movie!", new_movie_path %>
<hr>
<%= render 'search' %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= render 'show' %>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Back to all movies", movies_path %>
<hr>
<% @users.each do |user| %>
    <h2><%= link_to user.email, user_path(user) %></h2>
    <h3><%= user.full_name %></h3>
    <hr>
<% end %></hr>

app/views/users/new.html.erb
<%= link_to "View all movies", movies_path %>
<h1>Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Back to all movies", movies_path %>
<hr>
    <h2><%= @user.email %></h2>
    <h3><%= @user.full_name %></h3>
    <hr>